komodo-core/src/main/resources/org/komodo/core/repository/local-repository-config.json, komodo-core/src/test/java/org/komodo/core/AbstractLoggingTest.java, komodo-core/src/test/java/org/komodo/core/internal/TestObjectOperations.java, komodo-core/src/test/java/org/komodo/core/repository/TestLocalRepositoryPersistence.java, komodo-metadata-instance/pom.xml, komodo-metadata-instance/src/main/java/org/komodo/metadata/DefaultMetadataInstance.java, komodo-openshift/scripts/komodo-teiid-wildfly-swarm-s2i.json, komodo-parent/pom.xml, komodo-spi/src/main/java/org/komodo/spi/constants/SystemConstants.java, komodo-spi/src/main/java/org/komodo/spi/repository/PersistenceType.java, komodo-utils/src/test/java/org/komodo/utils/TestKLog.java, server/komodo-rest/docker/Dockerfile, server/komodo-rest/pom.xml, server/komodo-rest/src/main/java/org/komodo/rest/ApplicationProperties.java, server/komodo-rest/src/main/java/org/komodo/rest/AuthHandlingFilter.java, server/komodo-rest/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-rest/src/main/java/org/komodo/rest/KomodoService.java, server/komodo-rest/src/main/java/org/komodo/rest/TeiidSwarmMetadataInstance.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoMetadataService.java, server/komodo-rest/src/main/webapp/WEB-INF/web.xml, server/komodo-rest/src/main/webapp/index.html, server/komodo-rest/src/test/java/org/komodo/rest/service/AbstractFrameworkTest.java
1) Upgraded Teiid version to 10.0.0.Final
2) Also upgraded the WF-Swarm to reflect the version of the Teiid.
3) Changed the maven group ids to reflect the new version
4) Added a dependency on https://github.com/teiid/kubernetes-service-catalog-client project, which is library required to interact with service catalog (this needs to put in maven central too)
5) Added code to create a docker image based on F8 docker plug-in. This is helpful in releasing a final image, which is tested with the template image at https://github.com/rareddy/osb-data-services This project will be merged with @shawkins work on community-based images. These would be community deliverables.
6) The above template uses "oauth-proxy" to let user login into OpenShift, which is a http proxy
7) Based on headers from the …
=> TEIIDTOOLS-283

.s2i/bin/assemble, komodo-openshift/scripts/komodo-os-setup.sh, komodo-openshift/scripts/komodo-teiid-wildfly-swarm-s2i.json, settings.xml
* To improve incremental build performance, the maven dependency repos can
be mirrored locally using nexus (requires separate nexus server).
* Adds custom extended assemble script which reads the MAVEN_MIRROR URL
and if defined adds it to the komodo settings.xml as a mirror
* settings.xml
* Provides empty mirrors tags for placeholder
* komodo*.json
* Adds MIRROR URL env variable to template
* Refactors komodo git url as env variable so it can be overridden
* komodo*.sh
* Exposes the MIRROR URL and SOURCE REPO as parameters to the script
=> Adds a MAVEN MIRROR URL variable to openshift build

README.md, build.sh, komodo-openshift/scripts/komodo-teiid-wildfly-swarm-s2i.json, server/komodo-rest/src/main/webapp/index.html
* This is necessary since no komodo REST API functions can be initiated
from this template without it, ie. even service/about fails without it
* Renames proxy to vdb-builder-gateway
* index.html
* Corrects relative link to api-docs
=> Integrate OAuth proxy into development template

komodo-relational/src/main/java/org/komodo/relational/dataservice/Dataservice.java, komodo-relational/src/main/java/org/komodo/relational/dataservice/internal/DataserviceImpl.java, komodo-relational/src/test/java/org/komodo/relational/dataservice/internal/DataserviceImplTest.java, server/komodo-rest/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/dataservice/RestDataservice.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/json/DataserviceSingleSourceAttributesSerializer.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/json/KomodoJsonMarshaller.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/request/KomodoDataserviceSingleSourceAttributes.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoMetadataService.java, server/komodo-rest/src/test/java/org/komodo/rest/relational/RestDataserviceTest.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoDataserviceServiceTestInSuite.java
TEIIDTOOLS-323
(This PR has a companion beetle-studio PR)
- modifies DataserviceService rest method to accept multiple tables, which are then used to generate the service views
- modifies Dataservice getServiceView(s) to return array of view names rather than single view
- fixed associated tests
=> Dataservice multi-view support

server/komodo-rest/src/main/java/org/komodo/servicecatalog/PublishConfiguration.java, server/komodo-rest/src/main/java/org/komodo/servicecatalog/TeiidOpenShiftClient.java, server/komodo-rest/src/test/java/org/komodo/servicecatalog/TestVDBPublisher.java
* Before the VDB based service build is invoked check is added to make sure the base image exists, if not build ends up in error
* Added the CPU resource limits on VM based CGroups limits
* Also added a timeout for build configuration of 2 mins before it fails to finish the configuration, note this is configuration, not the build image itself, that could take more time.
* centralized all the user specific configuration to the central place in PublishConfiguration class
=> TEIIDTOOLS-384, TEIIDTOOLS-380, TEIIDTOOLS-373

komodo-core/src/main/java/org/komodo/core/KomodoLexicon.java, komodo-core/src/main/java/org/komodo/core/visitor/VdbNodeVisitor.java, komodo-parent/pom.xml, komodo-relational/src/main/java/org/komodo/relational/vdb/ModelSource.java, komodo-relational/src/main/java/org/komodo/relational/vdb/internal/ModelSourceImpl.java, komodo-spi/src/main/java/org/komodo/spi/lexicon/vdb/VdbLexicon.java, komodo-utils/src/test/java/org/komodo/test/utils/TestUtilities.java, komodo-utils/src/test/resources/org/komodo/test/utils/USStates-source-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/books.xml, komodo-utils/src/test/resources/org/komodo/test/utils/notranslator-descrip-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/parts_dynamic-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/parts_dynamic_withkeys-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/patients-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/portfolio-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/roles-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/sample-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/teiid-vdb-all-elements.xml, komodo-utils/src/test/resources/org/komodo/test/utils/tweet-example-vdb.xml, komodo-utils/src/test/resources/org/komodo/test/utils/usstates-dataservice/usstates-vdb.xml, server/komodo-rest/src/main/java/org/komodo/rest/relational/response/RestVdbModelSource.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/AbstractKomodoServiceTest.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoVdbServiceTestInSuite.java
* This property was temporarily located in KomodoLexicon but belongs in the
VdbLexicon and its requisite modeshape vdb prefix. Thus, it has been
pushed down to the teiid-modeshape project.
* To be more clearer, it has been renamed to the origin connection rather
than the associated connection.
* The property stores the name of the connection which is searched for in
the user's workspace before being returned. This may well change in the
future as connections are placed in a shared area.
* Change to original idea of storing the connection reference since this
'requires' a connection to be in the repository, otherwise it will not be
imported/exported. Better to get the property populated to ensure the
maximum information is retained.
* pom.xml
* Version of teiid-modeshape upgraded to bring …
=> Moves and renames model source's associated connection

komodo-core/src/test/java/org/komodo/core/visitor/TestDdlNodeVisitor.java, komodo-relational/src/main/java/org/komodo/relational/ViewDdlBuilder.java, komodo-relational/src/test/java/org/komodo/relational/ViewDdlBuilderTest.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java
Addresses a couple issues that were found during mongo testing.
- KomodoDataserviceService - the source tables were not being exported with constraints.  The constraints are required for mongo to work properly
- ViewDdlBuilder - array types were not being handled correctly.  now using same approach as DdlNodeVisitor.
- added test cases for DdlNodeVisitor and the ViewDdlBuilder
=> TEIIDTOOLS-312 support mongo source

server/komodo-rest/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/RelationalMessages.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoVdbService.java, server/komodo-rest/src/main/resources/org/komodo/rest/relational/relationalmessages.properties, server/komodo-rest/src/test/java/org/komodo/rest/service/ServiceTestUtilities.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/AbstractKomodoServiceTest.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoVdbServiceTestInSuite.java
Adds a view name validation service - can be used by client to validate view names to ensure the name contains valid chars, etc.  And to verify that a view with the same name does not already exist.
=> TEIIDTOOLS-427 Adds view name validation service

server/komodo-rest/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoMetadataService.java, server/komodo-rest/src/main/java/org/komodo/servicecatalog/TeiidOpenShiftClient.java
* Adds REST API method to KomodoMetadataService for fetching the publishing
logs for an individual virtualization being published.
* TeiidOpenShiftClient
* Uses the info, error & debug functions to add logging to the main log
file and to an additional file for the virt being published. This log
can then be preserved by OS' storage.
* The log file is available to be read by the REST API and returned as
content for display in the UI.
=> TEIIDTOOLS-420: Provides API for logging in publishing operations

server/komodo-rest/src/main/java/org/komodo/rest/relational/connection/RestSchemaNode.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoConnectionService.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoMetadataService.java
Adds path info on the schema nodes which are generated for connection schema.
- added path to the RestSchemaNode
- the createSchemaNodePath method in KomodoConnectionService generates the path.  The path is in the fqn format
- also made a minor simplification change in KomodoMetadataService for a prior issue
=> TEIIDTOOLS-463 Adds path info to schema nodes

server/komodo-rest/src/main/java/org/komodo/rest/KomodoService.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoVdbService.java, server/komodo-rest/src/test/java/org/komodo/rest/service/ServiceTestUtilities.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoVdbServiceTestInSuite.java
- Moved the code that deletes the editor state to KomodoService so that it can be used by both KomodoVdbService and KomodoUtilService
- Created a method in KomodoService that provides the same editor ID used by Beetle if given a VDB name and a View name
- Created helper method in ServiceTestUtilities to check to see if a specified editor state exists
- Created test in KomodoVdbServiceTestInSuite that verifies the editor state is deleted when a view is deleted
=> Fix for TEIIDTOOLS-471 Deleting a View Should Also Delete Editor State

komodo-relational/src/main/java/org/komodo/relational/profile/ViewEditorState.java, komodo-relational/src/main/java/org/komodo/relational/profile/internal/ProfileImpl.java, server/komodo-rest/src/main/java/org/komodo/rest/KomodoService.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-rest/src/test/java/org/komodo/rest/service/ServiceTestUtilities.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoDataserviceServiceTestInSuite.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoUtilServiceTestInSuite.java
- previous view editor state is deleted now before adding a new editor state
- when a virtualization is deleted all the editor states of it's views are also deleted
- added test cases
=> Fixes for TEIIDTOOLS-472 and TEIIDTOOLS-473

server/komodo-rest/src/main/java/org/komodo/rest/relational/json/ViewEditorStateSerializer.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoUtilServiceTestInSuite.java
- Minor change to KomodoUtilService.  Transfers the complete status for the ViewDefinition.  Also added to unit test.
- Change to ViewEditorStateSerializer isComplete.  The commands are not required for state to be complete.
=> TTOOLS-477 Fix issue with UtilService

server/komodo-rest/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-rest/src/test/java/org/komodo/rest/service/unit/KomodoUtilServiceTestInSuite.java
- changed the stashViewEditorState method to stashViewEditorStates.  The method now takes an array of editor states, rather than a single state - this allows bulk creation of views.
- adapted the unit tests.
=> TEIIDTOOLS-488 Add ability to bulk stash editorStates

komodo-core/src/main/java/org/komodo/core/KomodoLexicon.java, komodo-core/src/main/resources/config/komodo.cnd, komodo-relational/src/main/java/org/komodo/relational/Messages.java, komodo-relational/src/main/java/org/komodo/relational/RelationalModelFactory.java, komodo-relational/src/main/java/org/komodo/relational/profile/SqlComposition.java, komodo-relational/src/main/java/org/komodo/relational/profile/SqlProjectedColumn.java, komodo-relational/src/main/java/org/komodo/relational/profile/ViewDefinition.java, komodo-relational/src/main/java/org/komodo/relational/profile/internal/SqlProjectedColumnImpl.java, komodo-relational/src/main/java/org/komodo/relational/profile/internal/ViewDefinitionImpl.java, komodo-relational/src/main/resources/org/komodo/relational/messages.properties, komodo-spi/src/main/java/org/komodo/spi/repository/KomodoType.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/json/KomodoJsonMarshaller.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/json/SqlCompositionSerializer.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/json/SqlProjectedColumnSerializer.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/json/ViewDefinitionSerializer.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestSqlProjectedColumn.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestViewDefinition.java, server/komodo-rest/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestViewEditorState.java, server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-rest/src/test/java/org/komodo/rest/relational/json/ViewEditorStateSerializerTest.java
Adds a projected column array to the view definition.  This is the initial implementation which allows user selection of individual columns for the view.  It will be refined in future as more capabilities are added and refined.
- adds projectedColumns to the cnd under view definition.
- adds the associated SqlProjectedColumn repo object.  Currently the column info includes name, type, and selection flag
- adds the necessary rest classes and modifies existing classes
- updates the unit tests
=> TTOOLS-465 Adds projected columns to view definition

server/komodo-server/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-server/src/main/java/org/komodo/rest/relational/RelationalMessages.java, server/komodo-server/src/main/java/org/komodo/rest/relational/RestEntityFactory.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoMetadataService.java, server/komodo-server/src/main/resources/org/komodo/rest/relational/relationalmessages.properties, ui/beetle-lib/src/connections/add-connection-wizard/add-connection-wizard.component.ts, ui/beetle-lib/src/connections/shared/connection.service.ts, ui/beetle-lib/src/connections/shared/connections-constants.ts, ui/beetle-lib/src/connections/shared/mock-connection.service.ts
- changes the rest method naming from 'serviceCatalogSource' to 'syndesisSource'.  Also changes corresponding messages etc to correspond to naming changes
- update the corresponding usages in the UI
=> TEIIDTOOLS-549 Updates rest method naming for syndesis

pom.xml, server/pom.xml, ui/pom.xml
Move ng tests into a profile so they can be disabled in a headless build environment.
=> ng tests should be in a profile so they can be disabled in a headless build environment

server/komodo-server/src/main/java/org/komodo/rest/relational/dataservice/RestDataservice.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, server/komodo-server/src/test/java/org/komodo/rest/relational/RestDataserviceTest.java, server/komodo-server/src/test/java/org/komodo/rest/relational/json/DataserviceSerializerTest.java
Adds a 'publishedState' property to the RestDataservice response.  KomodoDataserviceService uses the openshiftClient to set the published state of the dataservice VDB.  The publishedState can be one of the BuildStatus states ( NOTFOUND, SUBMITTED, CONFIGURING, BUILDING, DEPLOYING, RUNNING, FAILED, CANCELLED ).
=> TTOOLS-592 Add publishedState to rest dataservice

server/komodo-core/src/main/java/org/komodo/core/KomodoLexicon.java, server/komodo-core/src/main/resources/config/komodo.cnd, server/komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java, server/komodo-relational/src/main/java/org/komodo/relational/profile/SqlComposition.java, server/komodo-relational/src/main/java/org/komodo/relational/profile/SqlProjectedColumn.java, server/komodo-relational/src/main/java/org/komodo/relational/profile/ViewDefinition.java, server/komodo-relational/src/main/java/org/komodo/relational/profile/internal/ViewDefinitionImpl.java, server/komodo-server/src/main/java/org/komodo/rest/KomodoRestV1Application.java, server/komodo-server/src/main/java/org/komodo/rest/relational/RelationalMessages.java, server/komodo-server/src/main/java/org/komodo/rest/relational/json/ViewDefinitionSerializer.java, server/komodo-server/src/main/java/org/komodo/rest/relational/json/ViewDefinitionStatusSerializer.java, server/komodo-server/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestViewDefinition.java, server/komodo-server/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestViewDefinitionStatus.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-server/src/main/resources/org/komodo/rest/relational/relationalmessages.properties
- Adds DDL property to the ViewDefinition.  This will allow the user to provide their own DDL for the view.
- In the ServiceVdbGenerator -  if the view DDL is provided, it is used - rather than generating the DDL
- added a new service method in KomodoUtilService to validate a ViewDefinition.  This method takes the DDL from the supplied ViewDefinition and validates it.  This service method needs work - the DDL importer is throwing and exception so the response it not consistent currently.
=> TTOOLS-630 Add service for validation of ViewDefinition

server/komodo-core/src/main/java/org/komodo/core/KomodoLexicon.java, server/komodo-core/src/main/resources/config/komodo.cnd, server/komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java, server/komodo-relational/src/main/java/org/komodo/relational/profile/ViewDefinition.java, server/komodo-relational/src/main/java/org/komodo/relational/profile/internal/ViewDefinitionImpl.java, server/komodo-server/src/main/java/org/komodo/rest/relational/json/ViewDefinitionSerializer.java, server/komodo-server/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestViewDefinition.java, server/komodo-server/src/main/java/org/komodo/rest/relational/response/vieweditorstate/RestViewEditorState.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-server/src/test/java/org/komodo/rest/relational/json/ViewEditorStateSerializerTest.java
[has corresponding PR in syndesis UI]
Adds 'isUserDefined' property on the ViewDefinition.
- If false, the ServiceVdbGenerator will generate DDL from the ViewDefinition settings and reset its DDL
- If true, the DDL is not generated - the DDL value is used as is.
=> TTOOLS-661 ViewDefinition improvement

server/komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java, server/komodo-relational/src/test/java/org/komodo/relational/ServiceVdbGeneratorTest.java, server/komodo-server/src/main/java/org/komodo/rest/relational/RelationalMessages.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-server/src/main/resources/org/komodo/rest/relational/relationalmessages.properties
- ServiceVdbGenerator now incorporates the table annotation into the view DDL, using the ViewDefinition description if available
- some modifcations to KomodoUtilService on the name validation check.  also added handling for the description.
=> TTOOLS-672 Incorporate description into view DDL

server/komodo-core/src/main/java/org/komodo/core/KEngineImpl.java, server/komodo-server/src/main/java/org/komodo/metadata/internal/DefaultMetadataInstance.java, server/komodo-server/src/main/java/org/komodo/metadata/internal/TeiidAdminImpl.java, server/komodo-server/src/main/java/org/komodo/metadata/internal/TeiidVdbImpl.java, server/komodo-server/src/main/java/org/komodo/openshift/PublishConfiguration.java, server/komodo-server/src/main/java/org/komodo/openshift/TeiidOpenShiftClient.java, server/komodo-server/src/main/java/org/komodo/rest/KomodoAutoConfiguration.java, server/komodo-server/src/main/java/org/komodo/rest/KomodoService.java, server/komodo-server/src/main/java/org/komodo/rest/relational/dataservice/RestDataservice.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoMetadataService.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoUtilService.java, server/komodo-server/src/main/java/org/komodo/rest/service/KomodoVdbService.java, server/komodo-server/src/main/java/org/komodo/rest/service/ServiceVdbGenerator.java, server/komodo-server/src/test/java/org/komodo/openshift/TestVDBPublisher.java, server/komodo-server/src/test/java/org/komodo/rest/relational/RestDataserviceTest.java, server/komodo-server/src/test/java/org/komodo/rest/relational/json/DataserviceSerializerTest.java, server/komodo-server/src/test/java/org/komodo/rest/service/KomodoMetadataServiceTest.java, server/komodo-server/src/test/java/org/komodo/rest/service/ServiceVdbGeneratorTest.java, server/komodo-spi/src/main/java/org/komodo/metadata/MetadataInstance.java, server/komodo-spi/src/main/java/org/komodo/metadata/runtime/TeiidVdb.java, server/komodo-spi/src/main/java/org/komodo/spi/KEngine.java
This removes the modeshape storage of the service vdb - leaving only the schema vdbs.  For now the refresh views service method is not doing anything, rather the service vdb is built on demand with publishing from the view editor states.  This of course could be refined such that the refresh method creates a deployed version of a virtualization specific vdb which could be reused if it exists on a publishing call.
=> Removing the modeshape service vdb

komodo-server/src/main/java/org/komodo/metadata/TeiidDataSource.java, komodo-server/src/main/java/org/komodo/metadata/internal/TeiidDataSourceImpl.java, komodo-server/src/main/java/org/komodo/openshift/TeiidOpenShiftClient.java, komodo-server/src/main/java/org/komodo/rest/KomodoAutoConfiguration.java, komodo-server/src/main/java/org/komodo/rest/V1Constants.java, komodo-server/src/main/java/org/komodo/rest/connections/SyndesisConnectionSynchronizer.java, komodo-server/src/main/java/org/komodo/rest/datavirtualization/RestDataVirtualization.java, komodo-server/src/main/java/org/komodo/rest/datavirtualization/v1/BaseEntityAdapter.java, komodo-server/src/main/java/org/komodo/rest/datavirtualization/v1/DataVirtualizationV1Adapter.java, komodo-server/src/main/java/org/komodo/rest/datavirtualization/v1/SourceV1.java, komodo-server/src/main/java/org/komodo/rest/datavirtualization/v1/ViewDefinitionV1Adapter.java, komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, komodo-server/src/main/java/org/komodo/rest/service/KomodoMetadataService.java, komodo-server/src/main/java/org/komodo/rest/service/KomodoUtilService.java, komodo-server/src/test/java/org/komodo/rest/service/IntegrationTest.java
Here is the single data virtualization import/export.  It uses:
get .../dataservices/name/export
post .../dataservices/import?virtualization=name
The import/export format is a zip file containing a dv.json and a dv-info.json file - which is basically the same approach as syndesis.  We don't yet need any handling of versioning beyond the usage of the adapter classes which means that we can change the other service methods and/or the database and not disturb the import/export format.
The get method does seem problematic - as described in another issue - it seems like gets under an resource path should be for that object or child information.  So it could just as easily be a post or moved to it's own service (I recall that komodo had an import/export service).
This does not attempt to …
=> TEIIDTOOLS-728 initial single virtualization export

komodo-core/src/main/java/org/komodo/WorkspaceManager.java, komodo-core/src/main/java/org/komodo/repository/DataVirtualizationRepository.java, komodo-core/src/main/java/org/komodo/repository/WorkspaceManagerImpl.java, komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java, komodo-server/src/main/java/org/komodo/rest/service/KomodoVdbService.java, komodo-server/src/test/java/org/komodo/rest/service/IntegrationTest.java, komodo-server/src/test/java/org/komodo/rest/service/KomodoDataserviceServiceTest.java
This makes the validation change mentioned on TEIIDTOOLS-737.  Once the ui is changed, we can then remove the KomodoVdbService.
=> TEIIDTOOLS-737 deprecating the validation methods
