teiid/teiid-syndesis

komodo-core-tests/pom.xml
komodo-core-tests/src/test/resources/org/komodo/repository/test/infinispan-file-cachestore-config.xml
komodo-core-tests/src/test/resources/org/komodo/repository/test/infinispan-leveldb-cachestore-config.xml
komodo-core/src/main/java/org/komodo/repository/KomodoTypeRegistry.java
komodo-core/src/main/resources/org/komodo/repository/local-repository-infinispan-config.xml
komodo-metadata-instance/src/main/java/org/komodo/metadata/DefaultMetadataInstance.java
komodo-metadata/pom.xml
komodo-modeshape-vdb/src/main/java/org/komodo/modeshape/visitor/DdlNodeVisitor.java
komodo-modeshape/pom.xml
komodo-parent/pom.xml
komodo-relational/src/main/java/org/komodo/relational/internal/TypeResolverRegistry.java
komodo-relational/src/main/java/org/komodo/relational/workspace/WorkspaceManager.java
komodo-spi/src/main/java/org/komodo/spi/metadata/MetadataNamespaces.java
komodo-spi/src/main/java/org/komodo/spi/utils/KeyInValueMap.java
komodo-test-utils/pom.xml
plugins/komodo-plugin-service/pom.xml
plugins/komodo-plugin-service/src/main/java/org/komodo/osgi/storage/StorageServiceProvider.java
pom.xml
server/komodo-rest/src/main/java/org/komodo/rest/schema/json/TeiidXsdReader.java
server/komodo-rest/src/main/webapp/WEB-INF/web.xml

Here is a set of initial commit.  The minor cleanup of the web.xml, keyinvaluehashmap, and realigning the dependencies.  This leaves the forked source in place for now, but does switch to using maven dependencies instead.

initial updates to teiid-komodo

---

komodo-utils-logger/src/main/java/org/komodo/logging/log4j/Log4jLoggerImpl.java

Resolves unit test NPE I encountered on local build.

Fix Unit Test Issue

---

server/komodo-rest/src/main/java/org/komodo/rest/relational/connection/RestSchemaNode.java
server/komodo-rest/src/main/java/org/komodo/rest/service/KomodoConnectionService.java

Adds service call in ConnectionService to return the schema for a connection.  This replaces the previous getTable/getTables calls which were removed.
- adds the service method
- adds SchemaNode object for storing the node info

TEIIDTOOLS-426 source schema service

---

server/komodo-rest/pom.xml
server/komodo-rest/src/main/java/org/komodo/servicecatalog/DataSourceDefinition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/AmazonS3Definition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/ExcelDefinition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/FileDefinition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/MongoDBDefinition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/ODataV4Definition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/SalesforceDefinition.java
server/komodo-rest/src/main/java/org/komodo/servicecatalog/datasources/WebServiceDefinition.java

* fixed some resource adapter creation properties
* Added example to teiid-throntail repo to showcase usage of salesforce connection standalone

TEIIDTOOLS-313: Adding salesforce connection capabilities

---

komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java
komodo-relational/src/test/java/org/komodo/relational/ServiceVdbGeneratorTest.java

Added DDL generation and backing unit tests

TTOOLS-465

---

komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java

Modifies DDL generation to correctly account for view column selection.
- in a couple places, now gather selected columns into a separate list first - then the sql is generated.  This allows correct placement of comma separators.
- now saving the selected projected view columns names.  Then the saved names are used to generate the SELECT sql, matching up to the correct source columns.
- some renaming of lists for clarification
- some minor fixes to eliminate compile warnings

TT-465 Adjustments to DDL generation

---

komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java

This is an additional change to fix issue with DDL generation from a ViewDefinition.  @rareddy this file was changed yesterday also, just wanted you to be aware

TT-465 adjust generated view DDL

---

ui/package.json
ui/public_api.ts

add separate entrypoint for ng-packagr

---

ui/src/app/dataservices/virtualization/view-editor/view-canvas/models/canvas-node.ts
ui/src/app/shared/property-form/property-control-type.enum.ts

- reorganized encodeId and decodeId functions for build
- removed commented out code in enum

corrects canvas-node functions

---

ui/src/app/app-routing.module.ts
ui/src/app/connections/connections.component.spec.ts
ui/src/app/dataservices/virtualization/view-editor/connection-table-dialog/connection-table-dialog.component.spec.ts
ui/src/app/dataservices/virtualization/view-editor/view-property-editors/property-editor/property-editor.component.spec.ts
ui/src/app/shared/page-error/page-error.component.spec.ts
ui/src/app/shared/page-not-found/page-not-found.component.spec.ts
ui/src/app/shared/property-form/property-control-type.enum.ts
ui/src/environments/environment.prod.ts
ui/src/environments/environment.ts
ui/src/main.ts

additional path changes for upgrade

angular6 upgrade - more path fixes

---

ui/src/app/core/about-dialog/about.service.ts
ui/src/app/core/app-settings.service.ts
ui/src/app/core/core.module.ts
ui/src/app/core/logger.service.ts
ui/src/app/core/mock-app-settings.service.ts
ui/src/app/dataservices/dataservices.module.ts
ui/src/app/dataservices/shared/dataservice.service.ts
ui/src/app/dataservices/shared/vdb.service.ts

- corrects issue with environment imports
- now exporting ViewEditorComponent in the dataservices module

resolve environment import issues

---

ui/projects/beetle-lib/src/connections/add-connection/add-connection.component.html
ui/projects/beetle-lib/src/connections/connections.component.html
ui/projects/beetle-lib/src/dataservices/create-views-dialog/create-views-dialog.component.ts
ui/projects/beetle-lib/src/dataservices/dataservices.component.html
ui/projects/beetle-lib/src/dataservices/dataservices.module.ts
ui/projects/beetle-lib/src/dataservices/test-dataservice/test-dataservice.component.html
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/add-composition-wizard/add-composition-wizard.component.ts
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/editor-views/editor-views.component.ts
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/editor-views/message-log/message-log.component.ts
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/view-editor.component.html
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/view-property-editors/projected-columns-editor/projected-columns-editor.component.ts
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/view-property-editors/property-editor/property-editor.component.ts
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/view-property-editors/view-property-editors.component.ts
ui/projects/beetle-lib/src/dataservices/virtualization/view-editor/views-list/views-list.component.ts
ui/projects/beetle-lib/src/shared/progress-dialog/progress-dialog.component.ts
ui/projects/beetle-lib/tsconfig.lib.json
ui/src/app/app-routing.module.ts
ui/src/app/app.component.html
ui/src/app/app.module.ts
ui/src/index.html
ui/tsconfig.json

- temporarily comment out breadcrumbs due to build issues
- additional selector changes to use 'btl' prefix
- added app routing module
- additional build fixes

Additional fixes for upgrade

---

ui/projects/beetle-lib/src/core/core.module.ts
ui/projects/beetle-lib/src/core/lib-content/lib-content.component.html
ui/projects/beetle-lib/src/core/lib-content/lib-content.component.spec.ts
ui/projects/beetle-lib/src/core/lib-content/lib-content.component.ts
ui/projects/beetle-lib/src/core/selection.service.ts
ui/projects/beetle-lib/src/core/vertical-nav/vertical-nav.component.html
ui/projects/beetle-lib/src/core/vertical-nav/vertical-nav.component.spec.ts
ui/projects/beetle-lib/src/dataservices/create-views-dialog/create-views-dialog.component.ts
ui/projects/beetle-lib/src/dataservices/dataservices-cards/dataservice-card/dataservice-card.component.html
ui/projects/beetle-lib/src/dataservices/dataservices-list/dataservices-list.component.html
ui/projects/beetle-lib/src/dataservices/shared/composition.model.ts
ui/projects/beetle-lib/src/public_api.ts
ui/projects/beetle-lib/src/shared/slide-in/slide-in.component.ts
ui/src/app/app.component.html
ui/src/app/app.module.ts

adding lib component.  Allows standalone operation, as well as content (minus vertical nav) to be used in another app.

ang6 - adding library component

---

ui/projects/beetle-lib/src/dataservices/dataservices.module.ts

export of TestDataserviceComponent is added to dataservices module

Adds missing export in dataservices module

---

README.md
server/komodo-server/src/main/java/org/komodo/rest/KomodoRestV1Application.java
server/komodo-server/src/main/java/org/komodo/rest/relational/RestEntityFactory.java
server/komodo-server/src/main/java/org/komodo/rest/relational/connection/RestSchemaNode.java
server/komodo-server/src/main/java/org/komodo/rest/relational/json/connection/ConnectionSerializer.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoConnectionService.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoMetadataService.java
ui/beetle-lib/src/connections/shared/connection.service.ts

- Moves a few service methods from KomodoConnectionService into KomodoMetadataService, and adapts to using the syndesis sources.
- More work to do, but this is a good start.  The adapted service methods tested ok via swagger api page
- added step to readme
- other misc formatting changes and compile warning fixes

TEIIDTOOLS-555 Adapt service methods to syndesis sources

---

ui/beetle-lib/package.json
ui/package.json

TEIIDTOOLS-555 Update ui lib version

---

server/komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java
server/komodo-relational/src/test/java/org/komodo/relational/ServiceVdbGeneratorTest.java
ui/beetle-lib/package.json
ui/beetle-lib/src/connections/connections.component.spec.ts
ui/beetle-lib/src/connections/connections.component.ts
ui/beetle-lib/src/connections/shared/connection.service.ts
ui/beetle-lib/src/dataservices/create-views-dialog/create-views-dialog.component.ts
ui/beetle-lib/src/dataservices/virtualization/view-editor/add-composition-wizard/add-composition-wizard.component.ts
ui/beetle-lib/src/dataservices/virtualization/view-editor/connection-table-dialog/connection-table-dialog.component.ts
ui/beetle-lib/src/dataservices/virtualization/view-editor/view-editor.component.ts
ui/beetle-lib/src/shared/test-data.service.ts
ui/package.json

- the komodo ServiceVdbGenerator was modified since we are no longer using our workspace Connection objects
- ui - changes to utilize the syndesisSourceStatus service
- ui - removed connection service calls, adapted others

TTOOLS-562 Adapts ServiceVdbGenerator

---

server/komodo-server/src/main/resources/s2i/template-pom.xml

fix for s2i template

---

server/komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java
server/komodo-relational/src/test/java/org/komodo/relational/ServiceVdbGeneratorTest.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoMetadataService.java

- Add service method to get schema for all available sources.
- Mod ServiceVdbGenerator due to publishing failure

TTOOLS-596 Add service method to get all schema

---

server/komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java

minor change to dataservice validation logic.  Now only validates the dataservice, does not consider service vdb

TTOOLS-630 dataservice validation mod

---

server/komodo-relational/src/main/java/org/komodo/relational/ServiceVdbGenerator.java
server/komodo-relational/src/test/java/org/komodo/relational/ServiceVdbGeneratorTest.java

- Fix issue with DDL generation when one of the columns is a keyword.  Now escaping the keyword
- Added test case

ENTESB-10795 Fix for view DDL generation

---

server/komodo-server/src/main/java/org/komodo/rest/relational/dataservice/RestDataservice.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java

Adds pod namespace and odata hostname (if available) onto the dataservice

ENTESB-10794 Add publishing info to virtualization

---

server/komodo-core/src/main/java/org/komodo/WorkspaceManager.java
server/komodo-core/src/main/java/org/komodo/datavirtualization/DataVirtualization.java
server/komodo-core/src/main/java/org/komodo/repository/DataVirtualizationRepository.java
server/komodo-core/src/main/java/org/komodo/repository/WorkspaceManagerImpl.java
server/komodo-core/src/test/java/org/komodo/repository/DataVirtualizationTest.java
server/komodo-server/src/main/java/org/komodo/openshift/BuildStatus.java
server/komodo-server/src/main/java/org/komodo/openshift/PublishConfiguration.java
server/komodo-server/src/main/java/org/komodo/openshift/TeiidOpenShiftClient.java
server/komodo-server/src/main/java/org/komodo/rest/V1Constants.java
server/komodo-server/src/main/java/org/komodo/rest/datavirtualization/RestDataVirtualization.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoDataserviceService.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoMetadataService.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoPublishingService.java
server/komodo-server/src/main/java/org/komodo/rest/service/KomodoVdbService.java
server/komodo-server/src/main/java/org/komodo/rest/service/ServiceVdbGenerator.java
server/komodo-server/src/test/java/org/komodo/openshift/StatusTest.java
server/komodo-server/src/test/java/org/komodo/rest/relational/DataserviceSerializerTest.java
server/komodo-server/src/test/java/org/komodo/rest/relational/RestDataserviceTest.java
server/komodo-server/src/test/java/org/komodo/rest/service/IntegrationTest.java
server/komodo-server/src/test/java/org/komodo/rest/service/KomodoDataserviceServiceTest.java
server/komodo-server/src/test/java/org/komodo/rest/service/ServiceVdbGeneratorTest.java

making sure the dv name can become a valid os name
also removing the remaining server layer method references to vdb names

TEIIDTOOLS-753 differentiating between the vdb name and the os name

---

server/komodo-server/src/main/java/org/komodo/openshift/TeiidOpenShiftClient.java

Reverts teiid/teiid-syndesis#226

Revert "ENTESB-10899"

---

komodo-server/src/main/java/org/komodo/openshift/TeiidOpenShiftClient.java
komodo-server/src/main/java/org/komodo/rest/connections/SyndesisConnectionMonitor.java
komodo-server/src/main/java/org/komodo/rest/connections/SyndesisConnectionSynchronizer.java
komodo-server/src/test/java/org/komodo/rest/service/IntegrationTest.java

adding a timer job for refresh and cleaning up removed

TEIIDTOOLS-789 TEIIDTOOLS-729

---

README.md

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Fix several typos in readme
